[package]
name    = "tree-fucker"
version = "0.1.0"
edition = "2024"

[workspace]
[workspace.lints]
cargo   = { implicit_features = "warn" }
clippy  = {}
rust    = {}
rustdoc = { all = "deny" }

[dependencies]
futures-channel = "0.3.34"
futures-core    = "0.3.34"
futures-util    = "0.3.34"
imbl            = "7.0.1"

[dependencies.tokio]
version  = "1.53.1"
features = ["rt", "time"]
optional = true

[dev-dependencies]
futures-executor = "0.3.34"

[features]
tokio = ["dep:tokio"]

[lints]
workspace = true
